#!/bin/bash

set -ex

echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/unsafe-io
echo 'Debug::pkgProblemResolver "true";' > /etc/apt/apt.conf.d/debug
echo 'Acquire::http { Proxy "http://localhost:3142"; };' > /etc/apt/apt.conf.d/cacher
echo 'APT::Get::AllowUnauthenticated "true";' > /etc/apt/apt.conf.d/unsigned
apt-get update

mv /usr/sbin/invoke-rc.d /usr/sbin/invoke-rc.d.bak
ln -s /bin/true /usr/sbin/invoke-rc.d

# Set up phone PPA.
# FIXME: this presently is done before removal although it would be more
#   reliable after, because we need it to supply our mangled session.
apt-get -y install software-properties-common
apt-add-repository -y ppa:plasma-phone/ppa
apt-add-repository -y ppa:plasma-phone/ci
#add repository which has packages built out of CI
apt-add-repository http://pangea-data-lax-dci.s3.amazonaws.com/dci/plasma-phone/debian
#key for above repository
sudo apt-key add - <<EOL
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1
 
mQINBFRXlYIBEADrbnEhGbFCjEkYASk95azW9YURTDcffWzTdlirg1wpHa3wAZwc
3+zL0xPpulQakKNGNmHxN3HIlKG6hURrJBPb259ODKuz6VoQLvAbD0j3xik9YJ1Y
uDc2xbMTvXj67OMchXdNjiJKd2/3I7TSB1Obtqm/y1bOKVoxauK4fXodiq7GUB8o
QseJ6K2/aob00ebwQsHGEjmV7Y5rRevKofb+NuR2pUsZf6lJwzJx3caNIZmktJFy
Hn1s4TGbBwDBrVMYSHm5TgS6LCNhKJ3XfztulsvyaE0pyvZxLv+L7FhEy6xA7W1L
ljcwMM7neGlGrKh9BkHV00TGlwpDGbzuCT3H/yUm+4N71o9hSbNGijvHmm6L1YGB
TDijosSPAFD8M2TMSpa5sQawRPe89IN29i+ZiyGlIF+SZT+yy1d1uqadHxf4lyuj
6mYkrZn2Zeozh/ZFim066Jtc3O4/ChITOZvZ20H03gZJIsNlkbZFgjG4itm0Bra6
C4plzSAkEeOIIIweJzXsSPZ/eTKOCPf7Iqijx1i31DVcV/d117vWcGzv8trQqvyi
wEQgP27xgy7x3FKdvpflSomftu29i5e4wTkFqaW7TpssVBscaiUj2YC5D1Bc+dn6
93dQoi7ZF4ofNV2va6YBnhZ89LUwjZBaZgAgyGwLA6cQfj+AI4dQ95xDbwARAQAB
tC1EZWJpYW4gQ0kgUGFja2FnZSBQdWJsaXNoZXIgPG51bGxAcGFuZ2VhLnB1Yj6J
AjcEEwEKACEFAlRXlYICGwMFCwkIBwMFFQoJCAsFFgMCAQACHgECF4AACgkQsr1N
9K8QcGmtNRAA4gzO1N0pgeldJwqA2fSCqxyUkyFJYN6nJ+iyx9c+/V1nlG0IR2h8
t0B89oGhkBLrSjVprLOvqBbe0Mr+WI8fsbGcZqzWkinC88HS4tKSG3mTb3zhHrPW
XXNgZBFoEzr9coK2FPb1Wf+OZlt/1KYFD9fsXH09t7S65+LGN6Rwt90HRM/rLQhS
7QZEDGTekbfEFEWU4IhuadFd6Iogg3w/3Ak4jLn3AZl6C4I9erxXlbd1nNXjh8Kh
v1oMQHxWBfQq7fSlk8T2e9UTETcQek3ySpoTRuwv/w6r+OZ3QY67zbdZrl7TLjwU
iOtAqOfvMH5MYAExlWgZ9QRFr1q9wBsyDZI6V977kvfgS2obrHL9JVJzcH7oLBz7
9ZBcLzpj4eJdSGVgffoAqZzNQA3QYg8y2GRHwR53jjs+5atMaEWazRdZbtoYTr/G
GeJgPYw9q9+L/XoYLC9K3SW/e7tgnAxRXaX8puQkqEtSGxQbrnI2KAzXKtvzolhJ
GZCJiO0hg8SivtuaIUOyg2ppJ7GL8yDTbqeEv/vuR6u3FIInf5fkoq8UAVZW1kk9
E8h+hEwC9yn+GErgrWtihLpm7ZHIePi3vhCkwiMh7wJQSvHQfd4k037jj8v3Tf4M
a4hw1LvfpbOxVBwDdqEFgH6LQI5eXNGwR9Ps3F1KA3yNVI2FKbArVPQ=
=UBq7
EOL

apt-get update

# Hold ubuntu-touch-session at a managled version. We specifically break
# runtime dependencies as they include unity8. The package is however also
# apparently very important to the correct function of the image due to !unity
# bits.
apt-get install --force-yes -y \
  ubuntu-touch-session=0.108+15.04.20150407-0ubuntu1+kubuntu1
apt-mark hold ubuntu-touch-session

apt-get remove --purge -y \
  unity8 \
  lightdm \
  myspell-ca myspell-es myspell-it myspell-pl myspell-pt-br myspell-pt-pt \
  language-pack-touch-ast language-pack-touch-bg language-pack-touch-bs language-pack-touch-ca language-pack-touch-cs language-pack-touch-da language-pack-touch-de language-pack-touch-el language-pack-touch-en language-pack-touch-es language-pack-touch-eu language-pack-touch-fi language-pack-touch-fr language-pack-touch-gd language-pack-touch-gl language-pack-touch-he language-pack-touch-hu language-pack-touch-id language-pack-touch-it language-pack-touch-ja language-pack-touch-ko language-pack-touch-lt language-pack-touch-lv language-pack-touch-ms language-pack-touch-nb language-pack-touch-nl language-pack-touch-oc language-pack-touch-pl language-pack-touch-pt language-pack-touch-ro language-pack-touch-ru language-pack-touch-sk language-pack-touch-sl language-pack-touch-sr language-pack-touch-sv language-pack-touch-tr language-pack-touch-ug language-pack-touch-uk language-pack-touch-zh-hans language-pack-touch-zh-hant \
  ubuntu-keyboard \
  libmaliit-plugins0 \
  whoopsie \
  maliit-framework
# Possibly relevant. At least relevant enough to not be removed for the time
# being.
#   apg \
#   system-image-common \
#   system-image-dbus \
# account-plugin-facebook \
# account-plugin-flickr \
# account-plugin-google \
# account-plugin-twitter \
# adwaita-icon-theme \
# humanity-icon-theme \
# suru-icon-theme \
# indicator-bluetooth \
# indicator-keyboard \
# indicator-location \
# indicator-network \
# indicator-transfer \
# qtdeclarative5-ubuntu-contacts0.1 \
# qtdeclarative5-ubuntu-content1 \
# qtdeclarative5-ubuntu-telephony-phonenumber0.1 \
# qtdeclarative5-ubuntu-telephony0.1 \
# qtdeclarative5-ubuntu-ui-extras-browser-plugin \
# qtdeclarative5-ubuntu-ui-extras0.2 \
# qtdeclarative5-ubuntu-web-plugin \
# qtdeclarative5-ubuntuone1.0 \
# qtdeclarative5-usermetrics0.1 \
# qtubuntu-sensors \
# ubuntu-application-api2-test \
# ubuntu-application-api2-touch \
# ubuntu-download-manager \
# ubuntu-keyboard \
# ubuntu-location-provider-here \
# ubuntu-location-service-bin \
# ubuntu-mobile-icons \
# ubuntu-mono \
# ubuntu-push-client \
# ubuntu-system-settings \
# ubuntu-system-settings-online-accounts \
# ubuntu-upload-manager \
# ubuntuone-client-data \
# unity-asset-pool \
# unity-control-center \
# unity-plugin-scopes \
# unity-scope-mediascanner2 \
# unity-settings-daemon \
# unity-system-compositor \
# ibus \
# nano \
# obex-data-server \
# qtmir-android \
# telephony-service \
# url-dispatcher \
# whoopsie-preferences \

# FIXME: powerd might be relevant but depends on ubuntu-apps-api2
# FIXME: there are plenty of relevant packages danling now, this needs
#   a full review of dangling packages and removal if not wanted or holding
#   via some meta if wanted.

apt-get -yf install
# Hybris
apt-get install -y \
  libhybris \
  libhybris-common1 \
  libhybris-test \
  libhybris-utils
# Foundation wiring we will need to work with ubuntu-touch tooling.
# This might also need parts of ubuntu-touch-session
apt-get install -y \
  initramfs-tools-ubuntu-touch \
  ubuntu-touch-generic-initrd \
  ubuntu-touch-customization-hooks \
  system-image-common \
  system-image-dbus \
  system-image-cli \
  apparmor
# More Foundation. In particular everything here is related to enabling
# the phablet user which is an extrausers user.
apt-get install -y \
  lxc-android-config \
  libnss-extrausers \
  libpam-modules \
  libpam-modules-bin \
  vim
# KF5 Stack
apt-get install -y \
  konsole \
  kwin \
  kwin-hwcomposer-backend \
  plasma-phone-components \
  qtwayland5 \
  xwayland \
  simplelogin \
  qtdeclarative5-private-dev \
  qml-module-org-kde-* \
  plasma-phone-dev-setup \
  plasma-phone-settings \
  kpackagelauncherqml
# Applications
apt-get install -y \
  voicecall \
  plasma-nm \
  plasma-camera \
  plasma-maliit-framework \
  plasma-maliit-plugins \
  plasma-sdk \
  plasma-settings
apt-get remove mtp-server
apt-get install -y mtp-server

apt-get -y clean

# plasma framework looking in the wrong place, this should go away when
# we work out why, maybe just an old version of plasma-framework
cp /usr/lib/arm-linux-gnueabihf/plugins/plasma/applets/plasma_* /usr/lib/arm-linux-gnueabihf/qt5/plugins/

# Cleanup
rm -f /etc/dpkg/dpkg.cfg.d/unsafe-io \
      /etc/apt/apt.conf.d/debug \
      /etc/apt/apt.conf.d/cacher
mv /usr/sbin/invoke-rc.d.bak /usr/sbin/invoke-rc.d

# Rename the simplelogin job to lightdm.
# A lot of the ubuntu-touch jobs do explicitly "start/stop on lightdm" which
# means they will not work without the job.
# This includes important bits such as adbd, so to work around this we simply
# pretend that simplelogin is lightdm. For the time being anyway.
mv /etc/init/simplelogin.conf /etc/init/lightdm.conf

# Make this chroot larger so we end up with a larger / on the final phone install
# make 10 of them because 1 large file, even if it's empty, makes gzip take up too much
# memory on the server and crap out
# for asdf in `seq 1 10`; do fallocate -l 100M SPACE-FILE${asdf}; done
