#!/bin/bash

set -ex

echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/unsafe-io
echo 'Debug::pkgProblemResolver "true";' > /etc/apt/apt.conf.d/debug
echo 'Acquire::http { Proxy "http://localhost:3142"; };' > /etc/apt/apt.conf.d/cacher
echo 'APT::Get::AllowUnauthenticated "true";' > /etc/apt/apt.conf.d/unsigned
apt-get update

mv /usr/sbin/invoke-rc.d /usr/sbin/invoke-rc.d.bak
ln -s /bin/true /usr/sbin/invoke-rc.d

# Set up phone PPA.
# FIXME: this presently is done before removal although it would be more
#   reliable after, because we need it to supply our mangled session.
apt-get -y install software-properties-common
apt-add-repository -y ppa:plasma-phone/ppa
apt-add-repository -y ppa:plasma-phone/ubuntu-apps
apt-add-repository -y multiverse
# MCI new CI combining all of the above nonsense into one CI source
add-apt-repository -y 'deb http://mobile.kci.pangea.pub vivid main'
# And key
apt-get install -y wget
pushd /tmp
rm key || true
wget http://mobile.kci.pangea.pub/Pangea%20CI.gpg.key -O key
apt-key add key
popd

# pin our repository
cat <<EOF > /etc/apt/preferences.d/phone-900
Package: *
Pin: origin "mobile.kci.pangea.pub"
Pin-Priority: 1100
EOF

# for some reason ubuntu touch is set to not install recommends but
# lots of our packages need them
rm /etc/apt/apt.conf.d/00recommends

apt-get update

# Hold ubuntu-touch-session at a managled version. We specifically break
# runtime dependencies as they include unity8. The package is however also
# apparently very important to the correct function of the image due to !unity
# bits.
apt-get install --force-yes -y \
  ubuntu-touch-session=0.108+15.04.20150407-0ubuntu1+kubuntu1
apt-mark hold ubuntu-touch-session

apt-get install -y powerd

apt-get remove --purge -y \
  unity8 \
  lightdm \
  myspell-ca myspell-es myspell-it myspell-pl myspell-pt-br myspell-pt-pt \
  language-pack-touch-ast language-pack-touch-bg language-pack-touch-bs language-pack-touch-ca language-pack-touch-cs language-pack-touch-da language-pack-touch-de language-pack-touch-el language-pack-touch-en language-pack-touch-es language-pack-touch-eu language-pack-touch-fi language-pack-touch-fr language-pack-touch-gd language-pack-touch-gl language-pack-touch-he language-pack-touch-hu language-pack-touch-id language-pack-touch-it language-pack-touch-ja language-pack-touch-ko language-pack-touch-lt language-pack-touch-lv language-pack-touch-ms language-pack-touch-nb language-pack-touch-nl language-pack-touch-oc language-pack-touch-pl language-pack-touch-pt language-pack-touch-ro language-pack-touch-ru language-pack-touch-sk language-pack-touch-sl language-pack-touch-sr language-pack-touch-sv language-pack-touch-tr language-pack-touch-ug language-pack-touch-uk language-pack-touch-zh-hans language-pack-touch-zh-hant \
  ubuntu-keyboard \
  libmaliit-plugins0 \
  whoopsie \
  apport \
  maliit-framework \
  qtubuntu-media \
  telephony-service \
  account-plugin-google \
  account-plugin-twitter \
  account-plugin-flickr \
  account-plugin-facebook \
  adwaita-icon-theme \
  humanity-icon-theme \
  suru-icon-theme \
  ubuntu-touch \
  indicator-bluetooth \
  indicator-keyboard \
  indicator-location \
  indicator-network \
  indicator-transfer \
  mir-test-tools \
  account-polld \
  accountsservice-ubuntu-schemas \
  accountsservice-ubuntu-touch-schemas \
  address-book-service \
  apparmor-easyprof-ubuntu \
  bluetooth-touch \
  cameraplugin-aal \
  fonts-takao-pgothic \
  fonts-wqy-microhei \
  media-hub \
  mediascanner2.0 \
  fonts-lohit-deva \
  account-plugin-tools \
  account-plugin-twitter \
  account-plugin-facebook \
  account-plugin-flickr \
  account-plugin-ubuntuone \
  account-plugin-google \
  ubuntu-touch-customization-hooks \
  system-image-cli \
  unity8 \
  indicator-bluetooth \
  indicator-datetime \
  indicator-display \
  indicator-location \
  indicator-messages \
  indicator-network \
  indicator-power \
  indicator-sound \
  indicator-transfer \
  indicator-transfer-download-manager \
  unity-scope-scopes \
  unity-scope-click \
  unity-scope-mediascanner2 \
  url-dispatcher \
  thumbnailer-service \
  webbrowser-app \
  webapp-container \
  dialer-app \
  messaging-app \
  address-book-app \
  mediaplayer-app \
  syncevolution \
  sync-monitor-uoa \
  ubuntu-touch-settings \
  ubuntu-system-settings \
  ubuntu-system-settings-online-accounts \
  policykit-desktop-privileges \
  qtdeclarative5-ubuntu-ui-extras0.2 \
  qtorganizer5-eds \
  unity-webapps-qml \
  oxideqt-codecs-extra \
  ubuntu-location-provider-here \
  ubuntu-touch-sounds \
  bluez \
  gstreamer1.0-fluendo-mp3 \
  gir1.2-notify-0.7 \
  libsmltk0 \
  gettext \
  libnet-cpp1 \
  libubuntu-location-service2 \
  libgstreamer-plugins-bad1.0-0 \
  folks-common \
  libnet1 \
  tone-generator \
  friends \
  libcontent-hub0 \
  nano \
  libical1a \
  libcapnp-0.4.0 \
  unity-plugin-scopes \
  libdee-qt5-3 \
  debsig-verify \
  urfkill \
  mir-client-platform-android3 \
  syncevolution-provider-uoa \
  dbus-property-service \
  smemstat \
  libgnome-keyring-common \
  qtmir-android \
  qml-module-qtqml-statemachine \
  ubuntuone-credentials-common \
  libgweather-3-6 \
  sqlite3 \
  libmediascanner-2.0-3 \
  qtdeclarative5-ubuntu-content1 \
  mir-utils \
  strace \
  qtdeclarative5-accounts-plugin \
  iw \
  qtdeclarative5-usermetrics0.1 \
  libubuntu-upload-manager-common1 \
  ubuntu-html5-ui-toolkit \
  libpgm-5.1-0 \
  libebook-1.2-14 \
  liboxideqt-qmlplugin \
  libpresage-data \
  libcamel-1.2-49 \
  libgoa-1.0-common \
  libgeoclue0 \
  libqt5keychain0 \
  libboost-serialization1.55.0 \
  trust-store-bin \
  libunity-scopes-json-def-desktop \
  libboost-regex1.55.0 \
  qml-module-qt-websockets \
  syncevolution-common \
  libfolks25 \
  libqmenumodel0 \
  evolution-data-server \
  unity-schemas \
  libsecret-common \
  libumockdev0 \
  libsecret-1-0 \
  gstreamer0.10-pulseaudio \
  packagekit-plugin-click \
  qtdeclarative5-ubuntu-history0.1 \
  libexif12 \
  libqt5location5-plugins \
  libpkcs11-helper1 \
  whoopsie-preferences \
  libtinyxml2-2 \
  libmessaging-menu0 \
  libsignon-glib1 \
  eventstat \
  qtdeclarative5-poppler1.0 \
  libmedia-hub-client3 \
  qml-module-qtpositioning \
  libnss3 \
  libsystemsettings1 \
  friends-dispatcher \
  libsynthesis0 \
  liboauth0 \
  libtimezonemap1 \
  libhud2 \
  libcurl3 \
  qml-module-qtsensors \
  rfkill \
  libqt5feedback5 \
  liburl-dispatcher1 \
  libqdjango-db0 \
  upstart-watchdog \
  qtvideonode-plugin \
  qtdeclarative5-qtmir-plugin \
  syncevolution-libs-gnome \
  libpresage1 \
  qtdeclarative5-friends0.2 \
  libpcap0.8 \
  gir1.2-freedesktop \
  libgdata19 \
  libmirplatform10 \
  gstreamer0.10-plugins-good \
  content-hub \
  qtubuntu-sensors \
  libneon27-gnutls \
  libfaad2 \
  dconf-cli \
  libdbusmenu-glib4 \
  libmirclient8 \
  gir1.2-ebookcontacts-1.2 \
  libmirserver34 \
  ubuntu-location-service-bin \
  fonts-liberation \
  libmedia-hub-common3 \
  liblzo2-2 \
  qmlscene \
  libedata-book-1.2-20 \
  libebook-contacts-1.2-0 \
  libtimezonemap-data \
  libgnome-keyring0 \
  qml-module-qtlocation \
  sync-monitor-helper \
  ltrace \
  qmenumodel-qml \
  libunity-api0 \
  ubuntu-mobile-icons \
  libgdata-common \
  usensord \
  qtdeclarative5-ofono0.2 \
  usermetricsservice \
  gir1.2-networkmanager-1.0 \
  libunistring0 \
  libopencore-amrnb0 \
  powerstat \
  libsodium13 \
  qtdeclarative5-ubuntu-download-manager0.1 \
  unity-system-compositor \
  evolution-data-server-common \
  gstreamer1.0-hybris \
  libindicator-transfer0 \
  gir1.2-dee-1.0 \
  nuntium \
  ubuntu-application-api3-touch \
  libtrust-store1 \
  libunity-action-qt1 \
  obexd-server \
  mir-graphics-drivers-android \
  qtdeclarative5-gsettings1.0 \
  libmircommon4 \
  libfolks-eds25 \
  gsettings-ubuntu-schemas \
  pulseaudio-module-trust-store \
  libqt5positioning5-plugins \
  libzen0 \
  libubuntu-platform-hardware-api2 \
  ubuntu-upload-manager \
  gir1.2-accounts-1.0 \
  libubuntu-application-api2 \
  qtdeclarative5-ubuntu-keyboard-extensions0.1 \
  qtubuntu-android \
  qtdeclarative5-unity-notifications-plugin \
  libmms0 \
  wireless-tools \
  qtdeclarative5-ubuntu-syncmonitor0.1 \
  libgee2 \
  alsa-base \
  gir1.2-gdkpixbuf-2.0 \
  libopenobex1 \
  signon-apparmor-extension \
  libmirprotobuf0 \
  ubuntu-application-api2-test \
  python3-crypto \
  libtinyxml2.6.2 \
  libqt5location5 \
  libfriends0 \
  libunity9 \
  gir1.2-edataserver-1.2 \
  ubuntuone-client-data \
  libusermetricsoutput1 \
  qml-module-qt-labs-settings \
  gir1.2-ubuntu-app-launch-2 \
  libopencore-amrwb0 \
  hunspell-fr \
  libzmqpp3 \
  syncevolution-dbus \
  qtdeclarative5-unity-action-plugin \
  gstreamer1.0-plugins-bad-videoparsers \
  python3-apport \
  qml-module-qtfeedback \
  libebackend-1.2-7 \
  libpay2 \
  libwhoopsie-preferences0 \
  libwhoopsie0 \
  libsbc1 \
  tcptraceroute \
  libqt5systeminfo5 \
  linux-sound-base \
  libphonenumber6 \
  libofono-qt1 \
  lsof \
  liboxideqtquick0 \
  libhistoryservice0 \
  libu1db-qt5-3 \
  libqt5websockets5 \
  watershed \
  ubuntu-ui-toolkit-theme \
  libqtubuntu-media-signals1 \
  libxmltok1 \
  obexd-client \
  libgoa-1.0-0b \
  libleveldb1 \
  libgweather-common \
  libgsettings-qt1 \
  gstreamer1.0-plugins-ugly-amr \
  libsyncevolution0 \
  gir1.2-signon-1.0 \
  telepathy-ofono-ril-mc-plugin \
  pulseaudio-module-droid \
  qtdeclarative5-u1db1.0 \
  libmediainfo0 \
  telepathy-ofono \
  health-check \
  mir-platform-graphics-android5 \
  libpcrecpp0 \
  history-service \
  oxideqt-codecs \
  libubuntu-download-manager-client1 \
  gstreamer1.0-plugins-bad-faad \
  libmirclient-debug-extension1 \
  forkstat \
  libpinyin4 \
  click-ubuntu-policy \
  ttf-ancient-fonts-symbola \
  libboost-log1.55.0 \
  gettext-base \
  python3-problem-report \
  myspell-el-gr \
  libnspr4 \
  ubuntu-application-api2-examples \
  libasprintf0c2 \
  thumbnailer-common \
  libusermetricsinput1 \
  libunity-protocol-private0 \
  fbset \
  qml-module-qtsysteminfo \
  libecal-1.2-16 \
  qml-module-ubuntu-onlineaccounts \
  libgdbussyncevo0 \
  libboost-locale1.55.0 \
  libsnappy1 \
  gir1.2-ebook-1.2 \
  libgeocode-glib0 \
  libunity-scopes3 \
  openvpn \
  libedataserver-1.2-18 \
  libqt5sensors5 \
  ubuntu-application-api2-touch \
  syncevolution-libs \
  libedata-cal-1.2-23 \
  telepathy-gabble \
  python3-oauthlib \
  qml-module-qtqml-models2 \
  libzmq3 \
  libnss3-nssdb \
  libjsoncpp0 \
  ofono-scripts \
  qtdeclarative5-qtfeedback-plugin \
  liboxideqtcore0 \
  ubuntu-sounds \
  unity-scope-click-departmentsdb

#apt-get -y autoremove

apt-get -yf install
# FIXME workaround for initramfs breaking :(
rm /var/lib/dpkg/triggers/update-initramfs
apt-get install -y --force-yes plasma-phone
apt-get remove -y mtp-server
apt-get install -y mtp-server

# https://github.com/blue-systems/mobster/issues/153
apt-get install -y signon-ui-service signon-ui-x11
apt-get install -y telepathy-mission-control-5=1:5.16.3-1ubuntu1+phone1 libmission-control-plugins0=1:5.16.3-1ubuntu1+phone1 --force-yes
apt-get -y clean

# dirty way to make some more space
rm -rf /usr/share/doc/*

rm -rf /tmp/clicksies
mkdir -p /tmp/clicksies
pushd /tmp/clicksies
wget -O stallboard.click "https://www.dropbox.com/s/vd1swwzbxaj0ihw/com.popey.stallboard_0.2_all.click?dl=0"
pkcon install-local stallboard.click --allow-untrusted
wget -O file.click "https://www.dropbox.com/s/mkxpmb7h9jyp4g3/com.ubuntu.filemanager_0.4.373_armhf.click?dl=0"
pkcon install-local file.click --allow-untrusted
popd # back to pwd
rm -rf /tmp/clicksies

echo QT_QPA_PLATFORM=wayland >> /etc/environment
echo FORCE_RIL_NUM_MODEMS=1 >> /etc/environment
sed s,PATH.*,, /etc/environment -i
echo PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games >> /etc/environment
sed s,QT_IM_MODULE.*,, /etc/environment -i
echo QT_IM_MODULE=maliit >> /etc/environment


# Cleanup
rm -f /etc/dpkg/dpkg.cfg.d/unsafe-io \
      /etc/apt/apt.conf.d/debug \
      /etc/apt/apt.conf.d/cacher
mv /usr/sbin/invoke-rc.d.bak /usr/sbin/invoke-rc.d

# Reconfigure the resolvconf service
# NetworkManager is using resolvconf + dnsmasq combo
# resolvconf writes DNS resolution config in /run/resolvconf/resolv.conf
# however since first time installation is not run it will never be symlinked
# to /etc/resolv.conf, so run manually
# This eliminates the need for wifi-setup script and you can use any
# network connections on the fly
dpkg-reconfigure -f noninteractive resolvconf

# Rename the simplelogin job to lightdm.
# A lot of the ubuntu-touch jobs do explicitly "start/stop on lightdm" which
# means they will not work without the job.
# This includes important bits such as adbd, so to work around this we simply
# pretend that simplelogin is lightdm. For the time being anyway.
mv /etc/init/simplelogin.conf /etc/init/lightdm.conf

# Make this chroot larger so we end up with a larger / on the final phone install
# make 100 of them because 1 large file, even if it's empty, makes gzip take up too much
# memory on the server and crap out
# this doesn't work, it just takes up space without making more
#mkdir /pad
#cd /pad
#for asdf in `seq 0 1`; do truncate -s 10M padfile-${asdf}; done
