#!/bin/bash

set -ex

echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/unsafe-io
echo 'Debug::pkgProblemResolver "true";' > /etc/apt/apt.conf.d/debug
echo 'Acquire::http { Proxy "http://localhost:3142"; };' > /etc/apt/apt.conf.d/cacher
echo 'APT::Get::AllowUnauthenticated "true";' > /etc/apt/apt.conf.d/unsigned
apt-get update

mv /usr/sbin/invoke-rc.d /usr/sbin/invoke-rc.d.bak
ln -s /bin/true /usr/sbin/invoke-rc.d

# Set up phone PPA.
# FIXME: this presently is done before removal although it would be more
#   reliable after, because we need it to supply our mangled session.
apt-get -y install software-properties-common
apt-add-repository -y ppa:plasma-phone/ppa
apt-add-repository -y multiverse
# MCI new CI combining all of the above nonsense into one CI source
add-apt-repository -y 'deb http://mobile.kci.pangea.pub vivid main'
# And key
apt-get install -y wget
pushd /tmp
rm key || true
wget http://mobile.kci.pangea.pub/Pangea%20CI.gpg.key -O key
apt-key add key
popd

# pin our repository
cat <<EOF > /etc/apt/preferences.d/phone-900
Package: *
Pin: release o=vagrant
Pin-Priority: 1100
EOF

# for some reason ubuntu touch is set to not install recommends but
# lots of our packages need them
rm /etc/apt/apt.conf.d/00recommends

apt-get update

# Hold ubuntu-touch-session at a managled version. We specifically break
# runtime dependencies as they include unity8. The package is however also
# apparently very important to the correct function of the image due to !unity
# bits.
apt-get install --force-yes -y \
  ubuntu-touch-session=0.108+15.04.20150407-0ubuntu1+kubuntu1
apt-mark hold ubuntu-touch-session

apt-get remove --purge -y \
  unity8 \
  lightdm \
  myspell-ca myspell-es myspell-it myspell-pl myspell-pt-br myspell-pt-pt \
  language-pack-touch-ast language-pack-touch-bg language-pack-touch-bs language-pack-touch-ca language-pack-touch-cs language-pack-touch-da language-pack-touch-de language-pack-touch-el language-pack-touch-en language-pack-touch-es language-pack-touch-eu language-pack-touch-fi language-pack-touch-fr language-pack-touch-gd language-pack-touch-gl language-pack-touch-he language-pack-touch-hu language-pack-touch-id language-pack-touch-it language-pack-touch-ja language-pack-touch-ko language-pack-touch-lt language-pack-touch-lv language-pack-touch-ms language-pack-touch-nb language-pack-touch-nl language-pack-touch-oc language-pack-touch-pl language-pack-touch-pt language-pack-touch-ro language-pack-touch-ru language-pack-touch-sk language-pack-touch-sl language-pack-touch-sr language-pack-touch-sv language-pack-touch-tr language-pack-touch-ug language-pack-touch-uk language-pack-touch-zh-hans language-pack-touch-zh-hant \
  ubuntu-keyboard \
  libmaliit-plugins0 \
  whoopsie \
  apport \
  maliit-framework \
  qtubuntu-media \
  telephony-service \
  account-plugin-google \
  account-plugin-twitter \
  account-plugin-flickr
# Possibly relevant. At least relevant enough to not be removed for the time
# being.
#   apg \
#   system-image-common \
#   system-image-dbus \
# account-plugin-facebook \
# account-plugin-flickr \
# account-plugin-twitter \
# adwaita-icon-theme \
# humanity-icon-theme \
# suru-icon-theme \
# indicator-bluetooth \
# indicator-keyboard \
# indicator-location \
# indicator-network \
# indicator-transfer \
# qtdeclarative5-ubuntu-contacts0.1 \
# qtdeclarative5-ubuntu-content1 \
# qtdeclarative5-ubuntu-telephony-phonenumber0.1 \
# qtdeclarative5-ubuntu-telephony0.1 \
# qtdeclarative5-ubuntu-ui-extras-browser-plugin \
# qtdeclarative5-ubuntu-ui-extras0.2 \
# qtdeclarative5-ubuntu-web-plugin \
# qtdeclarative5-ubuntuone1.0 \
# qtdeclarative5-usermetrics0.1 \
# qtubuntu-sensors \
# ubuntu-application-api2-test \
# ubuntu-application-api2-touch \
# ubuntu-download-manager \
# ubuntu-keyboard \
# ubuntu-location-provider-here \
# ubuntu-location-service-bin \
# ubuntu-mobile-icons \
# ubuntu-mono \
# ubuntu-push-client \
# ubuntu-system-settings \
# ubuntu-system-settings-online-accounts \
# ubuntu-upload-manager \
# ubuntuone-client-data \
# unity-asset-pool \
# unity-control-center \
# unity-plugin-scopes \
# unity-scope-mediascanner2 \
# unity-settings-daemon \
# unity-system-compositor \
# ibus \
# nano \
# obex-data-server \
# qtmir-android \
# telephony-service \
# url-dispatcher \
# whoopsie-preferences \

# FIXME: powerd might be relevant but depends on ubuntu-apps-api2
# FIXME: there are plenty of relevant packages danling now, this needs
#   a full review of dangling packages and removal if not wanted or holding
#   via some meta if wanted.

apt-get -yf install
# FIXME workaround for initramfs breaking :(
rm /var/lib/dpkg/triggers/update-initramfs
apt-get install -y --force-yes plasma-phone
apt-get remove -y mtp-server
apt-get install -y mtp-server

apt-get -y clean

echo QT_QPA_PLATFORM=wayland >> /etc/environment
echo FORCE_RIL_NUM_MODEMS=1 >> /etc/environment
sed s,PATH.*,, /etc/environment -i
echo PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games >> /etc/environment

# Cleanup
rm -f /etc/dpkg/dpkg.cfg.d/unsafe-io \
      /etc/apt/apt.conf.d/debug \
      /etc/apt/apt.conf.d/cacher
mv /usr/sbin/invoke-rc.d.bak /usr/sbin/invoke-rc.d

# Rename the simplelogin job to lightdm.
# A lot of the ubuntu-touch jobs do explicitly "start/stop on lightdm" which
# means they will not work without the job.
# This includes important bits such as adbd, so to work around this we simply
# pretend that simplelogin is lightdm. For the time being anyway.
mv /etc/init/simplelogin.conf /etc/init/lightdm.conf

# Make this chroot larger so we end up with a larger / on the final phone install
# make 100 of them because 1 large file, even if it's empty, makes gzip take up too much
# memory on the server and crap out
# this doesn't work, it just takes up space without making more
#mkdir /pad
#cd /pad
#for asdf in `seq 0 1`; do truncate -s 10M padfile-${asdf}; done
