#!/bin/bash

# Copyright Jonathan Riddell 2015, may be copied under GNU GPL v2 or later
# download ubuntu touch, upload it to the arm server, download remastered image from arm server

SERVER=root@212.47.238.144

mkdir -p daily-preinstalled
cd daily-preinstalled

echo === downloading from cdimage.ubuntu.com
zsync http://cdimage.ubuntu.com/ubuntu-touch/daily-preinstalled/current/vivid-preinstalled-touch-armhf.tar.gz.zsync

echo === uploading to arm server
rsync -CvzapP --stats vivid-preinstalled-touch-armhf.tar.gz ${SERVER}:ubuntu-touch-remaster/

echo === extracting on arm server - this will take some time
ssh ${SERVER} rm -rf /root/ubuntu-touch-remaster/extract
ssh ${SERVER} mkdir -p /root/ubuntu-touch-remaster/extract
ssh ${SERVER} tar xf ubuntu-touch-remaster/vivid-preinstalled-touch-armhf.tar.gz -C ubuntu-touch-remaster/extract
echo === uploading remaster script on arm server
scp ../chroot-remaster ${SERVER}:ubuntu-touch-remaster/extract/
echo === setting up resolve.conf in chroot
ssh ${SERVER} cp /etc/resolv.conf ubuntu-touch-remaster/extract/etc/
echo === running remaster script on arm server
ssh ${SERVER} chroot ubuntu-touch-remaster/extract /chroot-remaster
echo === making a new tar - this takes an age
ssh ${SERVER} "cd /root/ubuntu-touch-remaster/extract; tar zcf vivid-preinstalled-touch-armhf.tar.gz *"
cd ..
echo === downloading tar
DATE=`date --rfc-3339='seconds' | sed "s, ,.," | sed s,\+.*,, | sed s,-,, | sed s,-,, | sed s,:,, | sed s,:,,`
mkdir -p remaster-proposed/daily-preinstalled/${DATE}
rsync -CvzapP --stats ${SERVER}:ubuntu-touch-remaster/extract/vivid-preinstalled-touch-armhf.tar.gz remaster-proposed/daily-preinstalled/${DATE}
echo === running shasum
cd remaster-proposed/daily-preinstalled/${DATE}
sha256sum vivid-preinstalled-touch-armhf.tar.gz > SHA256SUMS
cd -
